# 示例配置，请根据你的需求修改或添加多个服务。
# 每个服务必须包含以下字段：
# - name: 服务名称（自定义）
# - interface: 绑定网卡名（如 eth0）
# - knock_ports: 敲门端口序列
# - allow_port: 放行的目标端口（如 SSH 22）
# - expire_seconds: 授权持续时间（秒）
# - step_timeout_seconds: 每步敲门最大间隔（秒）
# - whitelist: 白名单列表 [ 如果没有白名单则将值变为 "[]"]
# 注意：127.0.0.1 默认不放行，有需要则需要添加至白名单
services:
  - name: webadmin
    interface: eth0
    knock_ports: [1111, 2222, 3333]
    allow_port: 99
    expire_seconds: 300
    step_timeout_seconds: 5
    whitelist: 
    - 127.0.0.1
